# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.5
  - nightly
#matrix:
#  allow_failures:
#    - julia: nightly
#  fast_finish: true
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
      os: linux
    - julia: nightly
      os: osx
  include:
    - stage: Documentation
      julia: 1.5
      script: julia --project=docs make.jl docs
      after_success: skip
  fast_finish: true
script:
  - travis_wait julia --code-coverage make.jl test
after_success:
  - julia make.jl codecov
